service:
  app.admin.category:
    class: AppBundle\Admin\CategoryAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Admin', label: "Category" }
    arguments: [~, AppBundle\Entity\Category, ~]
  app.admin.blog_post:
    class: AppBundle\Admin\BlogPostAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, label: Blog post }
    arguments: [~, AppBundle\Entity\BlogPost, ~]

